#!/bin/bash

SUM=`md5sum bin/ar71xx/openwrt-ar71xx-generic-carambola2-squashfs-sysupgrade.bin`
MD5=${SUM:0:32}
echo $MD5 > bin/ar71xx/vyacht-wifi-9.4.0-upgrade-1.3.16.bin
cat bin/ar71xx/openwrt-ar71xx-generic-carambola2-squashfs-sysupgrade.bin >> bin/ar71xx/vyacht-wifi-9.4.0-upgrade-1.3.16.bin


